"""Kilo agent: writes kilo.json with Databricks-backed providers.

Kilo CLI (@kilocode/cli) is a fork of OpenCode; it shares OpenCode's config
schema, provider model, and plugin system. This module mirrors opencode.py,
reading the same discovered `opencode_models` view from state, and isolating
Kilo via XDG_CONFIG_HOME (verified on kilo 7.3.1/7.4.1: Kilo reads only
$XDG_CONFIG_HOME/kilo/ and ignores the user's real ~/.config/kilo)."""

from __future__ import annotations

import json
import os
import re
import signal

from ucode.config_io import (
    APP_DIR,
    ToolSpec,
    apply_json_mcp_diff,
    backup_existing_file,
    deep_merge_dict,
    read_json_safe,
    write_json_file,
    write_text_file,
)
from ucode.databricks import (
    build_auth_token_argv,
    build_opencode_base_urls,
    get_databricks_token,
    model_token_limits,
)
from ucode.os_compatibility import subprocess_cross_os
from ucode.state import mark_tool_managed, save_state
from ucode.telemetry import agent_version, ug_version

from .args import LaunchOptions, explicit_model_arg_value, has_explicit_model_arg

KILO_XDG_CONFIG_HOME = APP_DIR / "kilo-xdg"
KILO_CONFIG_DIR = KILO_XDG_CONFIG_HOME / "kilo"
KILO_CONFIG_PATH = KILO_CONFIG_DIR / "kilo.json"
KILO_BACKUP_PATH = APP_DIR / "kilo-config.backup.json"
KILO_AUTH_PLUGIN_PATH = KILO_CONFIG_DIR / "plugin" / "ucode-auth.js"
KILO_NPM_PACKAGE = "@kilocode/cli"
# Minimum Kilo version whose plugin runtime invokes the `config()` hook that our
# auth plugin (ucode-auth.js) relies on to refresh Databricks tokens.
# Verified empirically (plugin `config()` probe):
#   7.2.1  -> hook does NOT fire (unsupported; 7.2.x is a noisy patch series)
#   7.2.25 -> hook fires
#   7.3.1  -> hook fires  <-- chosen floor: earliest clean minor boundary that works
#   7.4.1  -> hook fires
MINIMUM_KILO_VERSION = (7, 3, 1)
MINIMUM_KILO_VERSION_TEXT = "7.3.1"

SPEC: ToolSpec = {
    "binary": "kilo",
    "package": f"{KILO_NPM_PACKAGE}@7",
    "display": "Kilo",
    "config_path": KILO_CONFIG_PATH,
    "backup_path": KILO_BACKUP_PATH,
}

PROVIDER_KEYS: list[list[str]] = [
    ["provider", "databricks-anthropic"],
    ["provider", "databricks-google"],
    ["provider", "databricks-oss"],
]

_AUTH_PLUGIN_TEMPLATE = """// Generated by ucode. Keep Databricks auth fresh for model requests.
import { execFile } from "node:child_process"
import { promisify } from "node:util"

const DATABRICKS_PROVIDERS = new Set([
  "databricks-anthropic",
  "databricks-google",
  "databricks-oss",
])
const AUTH_COMMAND = __AUTH_COMMAND__
const REFRESH_SKEW_MS = 120_000
const run = promisify(execFile)

let accessToken
let expiresAt = 0
let refreshPromise

function cacheToken(value) {
  accessToken = value
  expiresAt = Infinity
  try {
    const claims = JSON.parse(Buffer.from(value.split(".")[1], "base64url").toString())
    if (typeof claims.exp === "number") expiresAt = claims.exp * 1000
  } catch {}
}

async function mintToken() {
  try {
    const { stdout } = await run(AUTH_COMMAND[0], AUTH_COMMAND.slice(1), { encoding: "utf8" })
    const token = stdout.trim()
    if (!token) throw new Error("returned an empty token")
    cacheToken(token)
  } catch (error) {
    const detail = String(error.stderr || error.message || "").trim()
    throw new Error("ug auth-token failed" + (detail ? ": " + detail : ""))
  }
}

function refreshToken() {
  if (!refreshPromise) refreshPromise = mintToken().finally(() => { refreshPromise = undefined })
  return refreshPromise
}

function requestWithToken(input, init, token) {
  const headers = new Headers(input instanceof Request ? input.headers : undefined)
  new Headers(init?.headers).forEach((value, key) => headers.set(key, value))
  headers.set("Authorization", "Bearer " + token)
  return { ...init, headers }
}

async function databricksFetch(input, init) {
  if (!accessToken || expiresAt <= Date.now() + REFRESH_SKEW_MS) await refreshToken()
  const attemptedToken = accessToken
  const response = await fetch(input, requestWithToken(input, init, attemptedToken))
  if (response.status !== 401) return response

  // Another concurrent request may already have refreshed this token.
  if (accessToken === attemptedToken) await refreshToken()
  return fetch(input, requestWithToken(input, init, accessToken))
}

export const UcodeDatabricksAuth = async () => ({
  config: async (config) => {
    for (const providerID of DATABRICKS_PROVIDERS) {
      const options = config.provider?.[providerID]?.options
      if (!options) continue
      if (!accessToken && typeof options.apiKey === "string") cacheToken(options.apiKey)
      options.fetch = databricksFetch
    }
  },
})
"""


def _parse_version(value: str) -> tuple[int, int, int] | None:
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", value)
    if match is None:
        return None
    major, minor, patch = match.groups()
    return int(major), int(minor), int(patch)


def _minimum_version_message() -> str | None:
    installed = agent_version(SPEC["binary"])
    parsed = _parse_version(installed)
    if parsed is None or parsed >= MINIMUM_KILO_VERSION:
        return None
    return (
        f"Kilo {installed} is too old. ucode requires Kilo "
        f"{MINIMUM_KILO_VERSION_TEXT} or newer for renewable Databricks authentication."
    )


def minimum_version_error() -> str | None:
    message = _minimum_version_message()
    if message is None:
        return None
    return f"{message} Update it with `npm install -g {SPEC['package']}`."


def render_auth_plugin(state: dict) -> str:
    """Render the local Kilo plugin that refreshes Databricks auth on demand."""
    argv = build_auth_token_argv(
        state["workspace"],
        state.get("profile"),
        use_pat=bool(state.get("use_pat")),
    )
    # A 401 must not return the same still-unexpired cached credential.
    argv.append("--force-refresh")
    return _AUTH_PLUGIN_TEMPLATE.replace("__AUTH_COMMAND__", json.dumps(argv))


def write_auth_plugin(state: dict) -> None:
    """Install the auto-discovered hook in ucode's isolated Kilo config."""
    # Derive the path so tests that redirect KILO_CONFIG_PATH stay isolated.
    path = KILO_CONFIG_PATH.parent / "plugin" / KILO_AUTH_PLUGIN_PATH.name
    write_text_file(path, render_auth_plugin(state))


def _resolve_model_selector(model: str, opencode_models: dict[str, list[str]]) -> str:
    """Return a Kilo model selector in provider/model form when possible."""
    if model.startswith(("databricks-anthropic/", "databricks-google/", "databricks-oss/")):
        return model

    anthropic_models = opencode_models.get("anthropic") or []
    if model in anthropic_models:
        return f"databricks-anthropic/{model}"

    gemini_models = opencode_models.get("gemini") or []
    if model in gemini_models:
        return f"databricks-google/{model}"

    oss_models = opencode_models.get("oss") or []
    if model in oss_models:
        return f"databricks-oss/{model}"

    return model


def resolve_explicit_model(model: str, state: dict) -> str:
    """Resolve and validate a model explicitly selected for a Kilo launch.

    Databricks model ids are exposed in family buckets in ucode state, while
    Kilo addresses those models through managed provider ids. Other
    provider/model selectors belong to Kilo and are passed through.
    """
    selector = model.strip()
    if not selector:
        raise RuntimeError("Kilo model must not be empty.")

    opencode_models = state.get("opencode_models") or {}
    resolved = _resolve_model_selector(selector, opencode_models)
    if "/" not in selector:
        if resolved != selector:
            return resolved
        hint = (
            "Run `ug configure --agent kilo` to discover models, then choose a "
            "discovered model id or pass a provider/model selector."
            if not opencode_models
            else "Choose a discovered model id or pass a provider/model selector."
        )
        raise RuntimeError(f"Kilo model '{selector}' is not configured. {hint}")

    provider, _, model_id = selector.partition("/")
    if not provider or not model_id:
        raise RuntimeError("Kilo model selector must use provider/model form.")
    managed_providers = {path[-1] for path in PROVIDER_KEYS}
    if provider not in managed_providers:
        return selector

    if _resolve_model_selector(model_id, opencode_models) == selector:
        return selector
    raise RuntimeError(
        f"Kilo model '{selector}' is not configured for managed provider '{provider}'."
    )


def _oss_model_overlay(model: str, ua_header: dict[str, str]) -> dict:
    """Per-model overlay for an OSS model entry.

    All OSS models carry the User-Agent header; models with known token limits
    also pin `limit` (context + output) so Kilo clamps `max_tokens` to a
    value the gateway accepts. Kilo's schema requires both fields together,
    so the limits table always supplies both."""
    overlay: dict = {"headers": ua_header}
    limits = model_token_limits(model)
    if limits is not None:
        overlay["limit"] = limits
    return overlay


def render_overlay(
    model: str,
    token: str,
    opencode_base_urls: dict[str, str],
    opencode_models: dict[str, list[str]],
) -> tuple[dict, list[list[str]]]:
    """Return (overlay, managed_key_paths) for kilo.json."""
    auth_headers = {"Authorization": f"Bearer {token}"}
    # Kilo hardcodes `User-Agent: opencode/<ver>` in session/llm.ts for
    # every provider, after the AI SDK's combineHeaders. The provider-level
    # `headers` are clobbered by that injection, but per-model `headers` are
    # merged AFTER and win — so the UA must live on each model entry.
    ua_header = {
        "User-Agent": f"ucode/{ug_version()} kilo/{agent_version('kilo')}",
    }

    anthropic_models = opencode_models.get("anthropic") or []
    gemini_models = opencode_models.get("gemini") or []
    oss_models = opencode_models.get("oss") or []

    providers: dict = {}
    keys: list[list[str]] = [["model"]]
    if anthropic_models:
        # @ai-sdk/anthropic injects `eager_input_streaming: true` on tool defs;
        # the Databricks gateway's strict validator rejects it, so we disable tool
        # streaming per-model. The setting lives in per-call providerOptions, which
        # Kilo reads from `models.<m>.options`, not provider `options`.
        anthropic_model_overlay = {
            "headers": ua_header,
            "options": {"toolStreaming": False},
        }
        providers["databricks-anthropic"] = {
            "npm": "@ai-sdk/anthropic",
            "options": {
                "baseURL": opencode_base_urls["anthropic"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": dict.fromkeys(anthropic_models, anthropic_model_overlay),
        }
        keys.append(["provider", "databricks-anthropic"])
    if gemini_models:
        providers["databricks-google"] = {
            "npm": "@ai-sdk/google",
            "options": {
                "baseURL": opencode_base_urls["gemini"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": {m: {"headers": ua_header} for m in gemini_models},
        }
        keys.append(["provider", "databricks-google"])
    if oss_models:
        providers["databricks-oss"] = {
            "npm": "@ai-sdk/openai",
            "options": {
                "baseURL": opencode_base_urls["oss"],
                "apiKey": token,
                "headers": auth_headers,
            },
            "models": {m: _oss_model_overlay(m, ua_header) for m in oss_models},
        }
        keys.append(["provider", "databricks-oss"])

    overlay: dict = {"model": _resolve_model_selector(model, opencode_models)}
    if providers:
        overlay["provider"] = providers
    return overlay, keys


def write_tool_config(
    state: dict,
    model: str,
    token: str | None = None,
) -> tuple[dict, str]:
    backup_existing_file(KILO_CONFIG_PATH, KILO_BACKUP_PATH)
    if token is None:
        token = get_databricks_token(state["workspace"], state.get("profile"))
    opencode_base_urls = state.get("base_urls", {}).get("opencode") or build_opencode_base_urls(
        state["workspace"]
    )
    overlay, managed_keys = render_overlay(
        model,
        token,
        opencode_base_urls,
        state.get("opencode_models") or {},
    )
    existing = read_json_safe(KILO_CONFIG_PATH)
    write_auth_plugin(state)
    providers = existing.get("provider")
    if isinstance(providers, dict):
        for stale in (
            "databricks-anthropic",
            "databricks-google",
            "databricks-oss",
        ):
            providers.pop(stale, None)
    merged = deep_merge_dict(existing, overlay)
    write_json_file(KILO_CONFIG_PATH, merged)
    state = mark_tool_managed(state, "kilo", managed_keys)
    save_state(state)
    return state, token


def build_mcp_server_entry(argv: list[str]) -> dict:
    # A `local` MCP server runs a command over stdio; `command` is the full
    # argv. ug registers the `ug mcp-proxy ...` bridge here so Kilo
    # never speaks HTTP+bearer directly — the proxy mints fresh tokens itself.
    return {
        "type": "local",
        "command": list(argv),
        "enabled": True,
    }


def write_mcp_server_config(name: str, argv: list[str]) -> bool:
    backup_existing_file(KILO_CONFIG_PATH, KILO_BACKUP_PATH)
    existing = read_json_safe(KILO_CONFIG_PATH)
    mcp_servers = existing.get("mcp")
    if not isinstance(mcp_servers, dict):
        mcp_servers = {}
    removed = name in mcp_servers
    mcp_servers[name] = build_mcp_server_entry(argv)
    existing["mcp"] = mcp_servers
    write_json_file(KILO_CONFIG_PATH, existing)
    return removed


def remove_mcp_server_config(name: str) -> bool:
    existing = read_json_safe(KILO_CONFIG_PATH)
    mcp_servers = existing.get("mcp")
    if not isinstance(mcp_servers, dict) or name not in mcp_servers:
        return False
    mcp_servers.pop(name)
    existing["mcp"] = mcp_servers
    write_json_file(KILO_CONFIG_PATH, existing)
    return True


def write_user_mcp_servers(add: dict[str, dict], remove: set[str]) -> set[str]:
    """Apply ``add``/``remove`` to Kilo's `mcp` table in a single read-modify-write. Returns the names actually removed."""
    return apply_json_mcp_diff(KILO_CONFIG_PATH, "mcp", add, remove, backup_path=KILO_BACKUP_PATH)


def default_model(state: dict) -> str | None:
    # Kilo does not support admin-managed configs (unlike Claude/Codex), so there is
    # no `*_default_model` override to honor here; the default is derived purely from
    # the discovered buckets (anthropic > gemini > oss), which Kilo shares with OpenCode.
    opencode_models = state.get("opencode_models") or {}
    anthropic = opencode_models.get("anthropic") or []
    if anthropic:
        return anthropic[0]
    gemini = opencode_models.get("gemini") or []
    if gemini:
        return gemini[0]
    oss = opencode_models.get("oss") or []
    return oss[0] if oss else None


def _configure_launch(state: dict, model: str | None = None) -> str:
    model = model or default_model(state)
    if not model:
        raise RuntimeError("No Kilo model is configured.")
    _, token = write_tool_config(state, model)
    return token


def build_runtime_env(token: str, state: dict | None = None) -> dict[str, str]:
    env = os.environ.copy()
    env["OAUTH_TOKEN"] = token
    # Isolation: like OpenCode, Kilo honors XDG_CONFIG_HOME. Pointing it at our
    # private dir makes Kilo read ONLY $XDG_CONFIG_HOME/kilo/ and ignore the user's
    # real ~/.config/kilo. Verified on kilo 7.3.1/7.4.1: config() plugin hook fires
    # (token refresh works) and `kilo mcp list` sees only our managed servers.
    # Note: KILO_CONFIG merely MERGES on top of the real config (not exclusive), so
    # it is not used for isolation.
    env["XDG_CONFIG_HOME"] = str(KILO_XDG_CONFIG_HOME)
    return env


def launch(state: dict, tool_args: list[str], *, options: LaunchOptions) -> None:
    """Launch Kilo with the selected model and on-demand token refresh."""
    model = explicit_model_arg_value(tool_args) or options.user_pinned_model
    if model is not None:
        model = resolve_explicit_model(model, state)
    token = _configure_launch(state, model)
    env = build_runtime_env(token, state)

    if model is not None and not has_explicit_model_arg(tool_args):
        try:
            separator = tool_args.index("--")
        except ValueError:
            separator = len(tool_args)
        tool_args = [
            *tool_args[:separator],
            "--model",
            model,
            *tool_args[separator:],
        ]

    proc = subprocess_cross_os.popen([SPEC["binary"], *tool_args], env=env)
    try:
        returncode = proc.wait()
    except KeyboardInterrupt:
        proc.send_signal(signal.SIGINT)
        returncode = proc.wait()

    raise SystemExit(returncode)


def validate_cmd(binary: str) -> list[str]:
    return [binary, "run", "say hi in 5 words or less"]
